### ISSUE TITLE
Generating Unicode Braille Patterns

### ISSUE THREAD

**Issue by reiner-dolp** [liblouis/liblouisutdml#24]
I am trying to generate [Unicode Braille Patterns](https://en.wikipedia.org/wiki/Braille_Patterns) by post processing the output of `file2brl`.

However, I do not understand what the default output format is. I suspected it to be [Braille ASCII](https://en.wikipedia.org/wiki/Braille_ASCII). However, this does not seem to be true: Providing the german word "höhe" as input and using the german grade 0 table (de-de-g0.utb) yields "h9he" instead of the expected "h[he". Whats the output format generated by the default tables?

**Comment by reiner-dolp** [comment]
I would consider this to be a "documentation issue", not a "question".

The functionality is actually built-in. Simply use the Unicode Braille Patterns Table (unicode.dis):

```
> lou_translate unicode.dis,de-de-g0.utb
höhe
\x2813\x282a\x2813\x2811
```

However, i still do not unterstand what the default output format is:

```
> lou_trace -f de-de-g0.utb 
höhe
h9he
1.	lowercase	h	125
2.	lowercase	ö	246
3.	lowercase	h	125
4.	lowercase	e	15

häuser
h`user
1.	lowercase	h	125
2.	lowercase	ä	345
3.	lowercase	u	136
4.	lowercase	s	234
5.	lowercase	e	15
6.	lowercase	r	1235
```

The documentation only mentions _"[...] It causes the dot patterns to be Unicode Braille rather than the liblouis representation"_ without defining the terms "liblouis representation" and "unicode braille".

**Comment by egli** [comment]
Unicode handling is notoriously broken with the liblouis tools such as `lou_translate` or `lou_trace`. I think I believe that I have fixed this in master (starting from liblouis/liblouis@e93cd548a930ef59fb78eb2873de191cdd62ccf0 it should work).

Regarding documentation I honestly would like to have better doc too. You can maybe ask on the mailing list for some advice. Also I would be happy to merge a patch that improves the documentation.

**Comment by reiner-dolp** [comment]
I compiled directly from source/the git repo and did not experience any problems. :)

A "Getting Started Guide" in the style of the [Elastichsearch-Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html) would be awesome. I am trying to write a short tutorial as soon as I am more confident with the tool.

**Comment by egli** [comment]
That would be great, thanks
