### ISSUE TITLE
Release Version Format

### ISSUE THREAD

**Issue by lots0logs** [liblouis/liblouisutdml#31]
Hi, Would it be possible for you not to use hyphens in your tagged releases? It would make this library easier to package since most package managers do not allow hyphens in versions (which means currently it's difficult to automate the packaging of this library).

**Comment by egli** [comment]
I presume you are referring to the alpha release. Once we'll make a regular release there shouldn't be a dash (`-`) in the version name anymore.

**Comment by lots0logs** [comment]
Yes, that's what I am referring to. The release tags created by github when you make a release allow for easy automation of packaging. Typically alpha and beta version markers come directly after the patch number (eg: `v2.7.0alpha1`). Obviously you can do whatever you like with your version. I just mentioned it  because I know that it would make this library easier to package for all the various linux distros out there :smile:

**Comment by egli** [comment]
I just tagged v2.7.0. Can I close this issue?

**Comment by egli** [comment]
I believe this has been fixed
