### ISSUE TITLE
Braille tables for simplified Chinese.

### ISSUE THREAD

**Issue by vgjh2005** [liblouis/liblouisutdml#34]
Hi:
I uploaded two braille tables to the project two years ago. But I know those files have some error. Now two braille tables have been made again completely. I download the file included in liblouis now to try it. I find that they are just made by pinyin simply. It is not enough to use. Because there are more prononciation in the same character in simplified Chinese. So we made a largest table to try to cover them as soon as possible. I will upload tables here. Please tell me if there are any error. 
In another hands, we need to seperate braille text by word or by a character because of complexity in simplified Chinese to help people to realize all braille text. I know there are a lot of word segmentation software now. Except for using software, is there any similar function in liblouis to do that? Thanks for reply.
[zh-chn1.txt](https://github.com/liblouis/liblouisutdml/files/1276501/zh-chn1.txt)
[zh-chn2.txt](https://github.com/liblouis/liblouisutdml/files/1276508/zh-chn2.txt)

**Comment by egli** [comment]
Hi @vgjh2005 presumably you are referring to the tables you submitted in liblouis/liblouis#159? 

I would love to integrate these tables. For that I need some information:
- [ ] are these new tables for mandarin or are they an improvements of some existing table?
- [ ] can these tables be licensed under LGPLv2.1+?
- [ ] who is the copyright holder?

**Comment by vgjh2005** [comment]
Hi:
Copyright  by XueJin and KongGuYouLing. They agree to use with gpl
v2.1+. These table are make by manually completely and don't base on
any existing tables. There are any quesstion, please tell me. Thanks!

2017-09-05 20:38 GMT+08:00, Christian Egli <notifications@github.com>:

**Comment by egli** [comment]
Presumably these tables were added in liblouis/liblouis#159, so closing this issue.
