### ISSUE TITLE
Providing Windows builds

### ISSUE THREAD

**Issue by JordyDew** [liblouis/liblouisutdml#55]
I personally really miss a pre-built version for Windows (Win32). I am really not into C/C++, but I like how LiblouisUTDML works. On Linux, the compilation occurs almost automatically, but on Windows, it is more like a nightmare to me...

**Comment by bertfrees** [comment]
There is now a Dockerfile to do a cross-compilation: https://github.com/liblouis/liblouisutdml/commit/aa8d30c630421b85e77f4df7767e529e4679ec2b

**Comment by bertfrees** [comment]
See https://github.com/liblouis/liblouisutdml/issues/66

**Comment by egli** [comment]
Pre-built versions are provided with each release now
