### ISSUE TITLE
Beveled fractions are not converted correctly to Nemeth

### ISSUE THREAD

**Issue by NSoiffer** [liblouis/liblouisutdml#60]
The test beveled fraction test (`mathml_nemeth/mfrac_02.test`) fails:

Image | ![image](https://user-images.githubusercontent.com/1545836/62981912-6b799e80-bddf-11e9-9ca3-74a1b02a4c97.png)
------------ | -------------
Output | `?A+B/C+D#`
Expected | `?A+B_/C+D#`

I believe the problem is that there is nothing that checks for the bevelled attr used in `mfrac`:
```
<mfrac bevelled="true">
```

**Comment by bertfrees** [comment]
Thanks Neil for the well explained issues.

**Comment by hammera** [comment]
This issue will be resolwed in #96 when merged.

Attila

**Comment by hammera** [comment]
The mathml_nemeth/mfrac_02.test are passed with Liblouis UTDML latest master branch version, because #96 are merged the master branch.
Anybody please close this issue.

Kind regards,

Attila
