### ISSUE TITLE
Build failure due to failing testsuite

### ISSUE THREAD

**Issue by raghavgururajan** [liblouis/liblouisutdml#70]
liblouisutdml = 2.8.0
liblouis = 3.14.0

LOG = https://bin.disroot.org/?4dfe40e68d629e03#4127Ery9UrUgsoTtzy7nFfZ26qBxiBKM2dpBN21TTbfd

**Comment by egli** [comment]
See also the [travis build log](https://travis-ci.org/github/liblouis/liblouisutdml/builds/716561779)

**Comment by egli** [comment]
Fixed by 52d44cdbc307d4e2ffc3ebe674745eb9d43ec337

Thanks for the report
