### ISSUE TITLE
Question - Is there any Python wrapper for liblouisutdml 

### ISSUE THREAD

**Issue by gonziee** [liblouis/liblouisutdml#73]
I have liblouis working under Python but could not get nemeth math to work, I just found out that this is not supported in liblouis and must be done in liblouisutdml with file2brl. Is there any chance to get a python wrapper for libluisutdml or are there technical limitations for this?

**Comment by egli** [comment]
Hi @gonziee 

To my knowledge there is no python wrapper for liblouisutdml. You might want to ask on the mailing list if other people have been or are working on such a thing.

There is definitely a chance to get a python wrapper for libluisutdml. It's just that somebody has to do it :-). You could do it yourself or hire someone to do it for you. The API of libluisutdml is not that huge so it shouldn't be that much work. You can probably steal a lot of the boilerplate from the liblouis python bindings.

**Comment by gonziee** [comment]
Thanks @egli 

Appreciate the confirmation, I will have a look how the wrapper for liblouis has been done, never done a c wrapper before but would be interesting to learn.

**Comment by egli** [comment]
@gonziee cool! Looking forward to your PR :-)
