### ISSUE TITLE
Add missing declarations of do_pagenum and utd2dsBible to liblouisutdml.h

### ISSUE THREAD

**Issue by pjfordham** [liblouis/liblouisutdml#85]
diff --git a/liblouisutdml/louisutdml.h b/liblouisutdml/louisutdml.h
index eb84639..39ff35d 100644
--- a/liblouisutdml/louisutdml.h
+++ b/liblouisutdml/louisutdml.h
@@ -365,6 +365,7 @@ void do_reverse (xmlNode * node);
 int do_boxline (xmlNode * node);
 void do_pagebreak (xmlNode *node);
 void do_linespacing (xmlNode * node);
+int do_pagenum ();
 int do_newpage ();
 int do_blankline ();
 int do_softreturn ();

diff --git a/liblouisutdml/louisutdml.h b/liblouisutdml/louisutdml.h
index 39ff35d..809f6c8 100644
--- a/liblouisutdml/louisutdml.h
+++ b/liblouisutdml/louisutdml.h
@@ -406,6 +406,7 @@ int wc_string_to_utf8 (const widechar * instr, int *inSize, unsigned
 void output_xml (xmlDoc *doc);
 int convert_utd ();
 int utd2bible (xmlNode * node);
+int utd2dsBible (xmlNode * node);
 int utd2brf (xmlNode * node);
 int utd2pef (xmlNode * node);
 int utd2transinxml (xmlNode * node);

**Comment by egli** [comment]
Thanks for the report
